expname: ${seq.name}-${appr.name}-${seed}-${now:%Y%m%d_%H%M%S}


#hydra:
#  run:
#    dir: ./outputs

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S_%f${uuid:}}

defaults:
  - appr: spg
  - seq: ???
  - backbone: alexnet
  - seed: seed_1
  - seed_pt: random


optuna:
  direction: maximize
  storage: sqlite:///history.db


nhid: 2048
device: cuda
epochs_max: 500
patience_max: 5

lr: 0.25
lr_min: 1e-3
lr_factor: 3

fed:
  alg: PI_Fed  # PI_Fed, FedAvg
  num_clients: 5
  task: img_cls # text_cls, img_cls

