expname: ${seq.name}-${appr.name}-${seed}-${now:%Y%m%d_%H%M%S}


#hydra:
#  run:
#    dir: ./outputs

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S_%f${uuid:}}

defaults:
  - appr: spg
  - seq: ???
  - backbone: alexnet
  - seed: seed_1
  - seed_pt: random


optuna:
  direction: maximize
  storage: sqlite:///history.db


nhid: 2048
device: cuda
epochs_max: 10
epochs_client: 10
patience_max: 10

lr: 0.1
lr_min: 1e-3
lr_factor: 3
eps: 1e-3

fed:
  alg: PI_Fed  # PI_Fed, FedAvg
  num_clients: [2, 2, 4, 2, 3, 4, 2, 3, 4, 2, 3, 2, 5, 4, 2, 4, 3, 4, 2, 2]
  task: img_cls # text_cls, img_cls

